#From Lesson 2: Jenkins Pipeline and Deployment, 7:05 of the video
---
- name: Deploy
  hosts: [localhost]
  gather_facts: false
  vars:
          ansible_python_interpreter: /usr/bin/python2
          application: nginx
  tasks:
          - name: create instances
            include_role:
                    name: create_instance
#          - name: setup DNS
#            include_role:
#                    name: route53
#
#- name: ELB tasks
#  hosts: [localhost]
#  vars:
#    ansible:python_interpreter: /usr/bin/python3
#  task:
#    - name: target group
#      include_role:
#        name: target_group
