#From Lesson 2: Jenkins Pipeline and Deployment, 7:23 of the video
#Security groups created with AWS docs:https://docs.aws.amazon.com/cli/latest/userguide/cli-services-ec3-sg.html
- name: Create the ELB only listening over port 80
  ec2_elb_lb:
    name: "{{ ELBNAME }}"
    state: present
    region: us-west-2
    zones:
      - us-west-2a
      - us-west-2b
    listeners:
      - protocol: http
        load_balancer_port: 80
        instance_port: 80
  register: elb

- name: Create EC2 instances
  ec2:
    key_name: YubiKey
    instance_type: t2.nano
    image: ami-0edb04b19b4552e64
    user_data: "{{ USERDATA }}"
    region: us-west-2
    group_id:
      - sg-0bc9cc8bf7031a432
      - sg-0cb8ed25dd127ac83
    wait: yes
    instance_tags:
      Name: web_server
      application: "{{ application }}"
    exact_count: 2
    count_tag:
      application: "{{ application }}"
  register: ec2_instances

- name: Wait for servers to come online
  wait_for:
    host: "{{ item.public_ip }}"
    port: 80
    timeout: 180
  with_items: "{{ ec2_instances.tagged_instances }}"
  ignore_errors: True

- name: Add each EC2 instance to the ELB
  ec2_elb:
    state: present
    ec2_elbs: "{{ ELBNAME }}"
    region: "{{ item.region }}"
    instance_id: "{{ item.id }}"
  with_items: "{{ ec2_instances.tagged_instances }}"
